bump version
conda-forge/zenodo_get-feedstock pull request #10
Opened 2024-05-15 14:13 UTC by casperdcl

- updated v1.6.1 (closes #6, closes #5, closes #4, closes #3)
- added user casperdcl (closes #9, fixes #8)
- deps: add humanize (fixes #6)

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered](https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

/CC @xhochy as requested in https://github.com/conda-forge/zenodo_get-feedstock/pull/9#issuecomment-2112615389

2024-05-15 14:14 UTC, casperdcl commented
@conda-forge-admin, please rerender

2024-05-16 10:02 UTC, xhochy requested changes

2024-05-16 10:02 UTC, xhochy commented on recipe/meta.yaml
> +  - pip
Please restore the formatting here. The old indentation is how it should be.

2024-05-16 10:08 UTC, casperdcl commented on recipe/meta.yaml
> +  - pip
Done

2024-05-17 12:27 UTC, xhochy approved these changes

2024-05-17 12:27 UTC, merged

2024-05-20 23:39 UTC, casperdcl commented
Thanks @xhochy - any idea why it's not building? ![](https://dev.azure.com/conda-forge/feedstock-builds/_apis/build/status/zenodo_get-feedstock?branchName=main)

2024-05-21 09:46 UTC, xhochy commented
No idea, make an empty commit to main. It could be that this was due to some glitch in Github's notification system.